### ISSUE TITLE
Map country iso to country full name?

### ISSUE THREAD

**Issue by wzup** [gosquared/flags#17]
Do you have a map for country iso to country full name? And vice versa would be great too.
```
{ us:  'United States' }
```

Because there is a real use case.
From third-party API we have data that has country as `alpha2` format.
You have both flags, country `iso` and country full name. But there is no map object to map `iso` to full name.

Do you have one? Would you please add it to repo?

**Comment by theKashey** [comment]
@wzup - take a look at [the country names](https://github.com/theKashey/the-country-names), as compact exports of [3166-db](https://github.com/esosedi/3166)

**Comment by wzup** [comment]
@theKashey 
Thanks! Exactly what I was looking for.
